### ISSUE TITLE
Theme suggestion

### ISSUE THREAD

**Issue by NoodlesDev987** [OreoKitten/PteroThemes#10]
Hi, could you please create theme with horizontal menu orientation?
Something like this:
![image](https://user-images.githubusercontent.com/81709846/116413693-265a0200-a838-11eb-8a6b-7ccda2e8cc4f.png)
![image](https://user-images.githubusercontent.com/81709846/116413726-2c4fe300-a838-11eb-8727-be8f0e8ff5df.png)

**Comment by Conjuringil** [comment]
No, that is a paid theme, I may be releasing a theme similar to this
![image](https://user-images.githubusercontent.com/38229170/116414076-cb0b1e00-a7fd-11eb-8ea0-a4e506ee5a85.png)
![image](https://user-images.githubusercontent.com/38229170/116414102-cfcfd200-a7fd-11eb-8199-f7c77cd49406.png)
![image](https://user-images.githubusercontent.com/38229170/116414122-d2cac280-a7fd-11eb-8a97-baf98350a7ae.png)

**Comment by NoodlesDev987** [comment]
Ok

**Comment by NoodlesDev987** [comment]
Btw are you planning to make some basic addons too?

**Comment by Conjuringil** [comment]
Maybe
