### ISSUE TITLE
Does not apply to user panel (With installer)

### ISSUE THREAD

**Issue by Zariaa27** [OreoKitten/PteroThemes#5]
As the title says: Does not apply to user panel (With installer)

**Comment by Conjuringil** [comment]
Was there any error or what is the result after running the script?

**Comment by Zariaa27** [comment]
The only thing the installer does is install the theme to the Admin Panel, is it supposed to do that?

**Comment by Conjuringil** [comment]
You didn't answer my question at all, was there any error.

**Comment by Zariaa27** [comment]
Sorry.. No there was not any errors

**Comment by Conjuringil** [comment]
Okay, i'll look into this later, i'm not on pc currently.

**Comment by Zariaa27** [comment]
All good, take your time!

**Comment by Conjuringil** [comment]
Could you send a picture of contents of the file in the location of /var/www/pterodactyl/resources/scripts/index.tsx

**Comment by Zariaa27** [comment]
https://share.zariaa.tk/s/tw4P1pf7ZR.tsx

**Comment by Conjuringil** [comment]
okay, could you try to do the following in the directory /var/www/pterodactyl 

rm -r .babel-plugin-macrosrc.js

yarn build:production

then do f5 on your panel, and see if that applies the theme

**Comment by Zariaa27** [comment]
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build:production'

**Comment by Conjuringil** [comment]
What directory are you in

**Comment by Zariaa27** [comment]
/var/www/pterodactyl

When I do ls:
app              CHANGELOG.md     database                    panel.tar.gz  SECURITY.md         tsconfig.json           artisan          composer.json    docker-compose.example.yml  public        server.php          vendor                  babel.config.js  composer.lock    Dockerfile                  README.md     storage             webpack.config.js       bootstrap        config           LICENSE.md                  resources     tailwind.config.js  yarn.lock               BUILDING.md      CONTRIBUTORS.md  package.json                routes        tests

**Comment by Conjuringil** [comment]
You do have yarn installed right?

**Comment by Zariaa27** [comment]
Yes I do

**Comment by Conjuringil** [comment]
Okay, could you message me on discord, notil.#2387

**Comment by Zariaa27** [comment]
When I do apt install yarn:
Note, selecting 'cmdtest' instead of 'yarn'
cmdtest is already the newest version (0.32.14.gcdfe14e-1).

**Comment by Zariaa27** [comment]
Done, dm'd you
