### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NoodlesDev987** [OreoKitten/PteroThemes#9]
I have added this addon to my panel and I use theme from this repo: https://github.com/HM4Development/mcpaste-addon/blob/v1.1/McPaste.tsx
But the button is not themed :/
![image](https://user-images.githubusercontent.com/81709846/116410821-6e2b5a00-a835-11eb-9361-2e41bc2bf162.png)

Can you please tell me how to modify the theme code to theme the button?

**Comment by Conjuringil** [comment]
I will make a pull request with a new theme and a update later today.

**Comment by NoodlesDev987** [comment]
Ok
